version: '3.9'

services:

  java_school_app:
    container_name: java_school_app
    image: school-app:1.0.0
    build: .
    ports: 
      - 8080:8080
    networks:
      - spring-network
    depends_on:
      - java_school_db

  java_school_db:
    container_name: java_school_db
    image: postgres
    ports: 
      - 5433:5432
    networks:
      - spring-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

networks:
  spring-network:


