spring:
  datasource:
    #url: jdbc:postgresql://dpg-cqo214jv2p9s73aj5c1g-a.oregon-postgres.render.com:5432/systemschool
    #username: systemschool_user
    #password: JRCYUVE3uphQA5sTfh6QCvhvpqF62StS
    url: jdbc:postgresql://localhost:5432/securitydb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000  # Tiempo de espera para obtener una conexión del pool en milisegundos (5 segundos)
      validation-timeout: 5000  # Tiempo de espera para validar una conexión en milisegundos (5 segundos)
      idle-timeout: 600000      # Tiempo de espera antes de que una conexión inactiva sea eliminada del pool en milisegundos (10 minutos)
      max-lifetime: 1800000     # Tiempo máximo de vida de una conexión en milisegundos (30 minutos)
      maximum-pool-size: 10     # Número máximo de conexiones en el pool (ajusta según tus necesidades)
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # a day
