spring:
  datasource:
    #url: jdbc:postgresql://dpg-cua3le5svqrc73dm0fs0-a.oregon-postgres.render.com:5432/schooldb_qz9u
    #username: systemschool_user
    #password: JRCYUVE3uphQA5sTfh6QCvhvpqF62StS
    #url: jdbc:postgresql://localhost:5432/securitydb
    url: ${URL}
    username: ${USERNAMEDB}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000  # Tiempo de espera para obtener una conexión del pool en milisegundos (5 segundos)
      validation-timeout: 5000  # Tiempo de espera para validar una conexión en milisegundos (5 segundos)
      idle-timeout: 600000      # Tiempo de espera antes de que una conexión inactiva sea eliminada del pool en milisegundos (10 minutos)
      max-lifetime: 1800000     # Tiempo máximo de vida de una conexión en milisegundos (30 minutos)
      maximum-pool-size: 10     # Número máximo de conexiones en el pool (ajusta según tus necesidades)
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:: 
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    secret-key: ${SECRET-KEY}
    expiration: 86400000 # a day
